name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019
    strategy:
      max-parallel: 4
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [x64, x86]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Setup to add MSBuild.exe to path
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild of plugin dll
      working-directory: src\windows\
      run: msbuild espeak-ng.sln /m /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}" /p:PlatformToolset="v142"

    - name: Archive artifacts for x64
      if: matrix.build_platform == 'x64'
      uses: actions/upload-artifact@v1
      with:
          name: plugin_dll_x64
          path: src\windows\${{ matrix.build_platform }}\${{ matrix.build_configuration }}\espeak.dll

    - name: Archive artifacts for x86
      if: matrix.build_platform == 'x86'
      uses: actions/upload-artifact@v1
      with:
          name: plugin_dll_x86
          path: src\windows\${{ matrix.build_configuration }}\espeak.dll
